
import { v4 as uuidv4 } from 'uuid';
export const HomeData = [
    
    {
        id: uuidv4(),
        title:"abella danger",
        aliases: ['Bella Danger', 'Bella Manriquez', 'Bella Mevzinsky', 'Isabella Danger'],
        to: '/abellaDanger',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/abellaDanger—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"alecia fox",
        aliases: ['Arya', 'Alicia Fox', 'Rita Mochalkina', 'Alecia', 'Lissa, Aljona'],
        to: '/alecia-fox',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/aleciaFox—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"alex grey",
        aliases: ["Alexia", "Asuna Luv"],
        to: '/alex-grey',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/alexGrey—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"alexa grace",
        aliases: ['Alexa of Nyce', 'Meghan Marie', 'Renee Marie'],
        to: '/alexaGrace',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/alexaGrace—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"alicia williams",
        aliases: ['Alicia Willia', 'Victoria'],
        to: '/alecia-williams',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/aliciaWilliams—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"alina lopez",
        aliases: ['Aleena Lopez', 'Aline Lopez'],
        to: '/alina-lopez',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/alinaLopez—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"alisa amore",
        aliases: ['Jessica Albanka', 'Alisa I', 'Inez Fulitko'],
        to: '/alisa-amore',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/alisaAmore—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"amanda lane",
        aliases: ["Amanda Aims", "Amanda Aimes", "Amanda Lane", "Amanda Lanes", "Tracy Maura"],
        to: '/amanda-lane',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/amandaLane—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"amber moore",
        // aliases: ['Armani Black', 'Armani'],
        to: '/amber-moore',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/amberMoore—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"amelie lou",
        aliases: ['Clarise', 'Alexa D', 'Amelie Lou', 'Amelielou', 'Clarice A', 'Clarice Azalia', 'Clarisa', 'Clarisse', 'Elvira U', 'Iona Tressa', 'Sonia Clarice', 'Sonia S'],
        to: '/amelie-lou',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/amelieLou—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"angelika grays",
        aliases: ['Angelika Greys', 'Sabrina Delight'],
        to: '/angelika-grays',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/angelikaGrays—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"apolonia lapiedra",
        aliases: ["Samantha Sánchez Martínez"],
        to: '/apolonia-lapiedra',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/apoloniaLapiedra—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"ariana Marie",
        // aliases: ['Ariana Marie', 'Ariana'],
        to: '/ariana-marie',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/arianaMarie—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"armani black",
        // aliases: ['Armani Black', 'Armani'],
        to: '/armani-black',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/armaniBlack—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"ashley lane",
        aliases: ["Ashley L"],
        to: '/ashley-lane',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/ashleyLane—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"august Ames",
        aliases: ['Mercedes Grabowski',],
        to: '/august-ames',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/augustAmes—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"avery cristy",
        aliases: ['Avery Christy'],
        to: '/avery-cristy',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/averyCristy—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"bella rolland",
        aliases: ['Bella Roland'],
        to: '/bella-rolland',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/bellaRolland—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"blake blossom",
        // aliases: ['Blake', 'Blake Blossom'],
        to: '/blake-blossom',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/blakeBlossom—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"blake eden",
        aliases: ['Blake', 'Blake Bartelli'],
        to: '/blake-cden',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/blakeEden—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"bunny colby",
        aliases: ['Nadya Nabakova', 'ANNA'],
        to: '/bunny-colby',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/bunnyColby—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"casey calvert",
        aliases: ['Sister Casey'],
        to: '/casey-calvert',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/caseyCalvert—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"chanel preston",
        aliases: ['Chanel Payton', 'Chanel Princeton', 'Chantel Preston', 'Rachel Ann Taylor', 'Rachel Taylor'],
        to: '/chanel-preston',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/chanelPreston—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"charlie red",
        aliases: ['Charlie', 'Hexchen', 'Kris', 'Mimi', 'Tereza'],
        to: '/charlie-red',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/charlieRed—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"christy white",
        aliases: ['Christina Andreadou', 'Christine White', 'Xristina Andreadou'],
        to: '/christyWhite',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/christyWhite—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"danni rivers",
        aliases: ['Dani Rivers'],
        to: '/danniRivers',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/danniRivers—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"dominika c",
        aliases: ['Dita', 'Domika C', 'Dominica C', 'Dominika', 'Dominika A', 'Dominika Chybova', 'Dominika85', 'Dominique'],
        to: '/dominika-c',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/dominikaC—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"elena koshka",
        // aliases: ['Elena', 'Elena Koshka'],
        to: '/elena-koshka',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/elenaKoshka—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"emelie crystal",
        aliases: ['Emelie Devot', 'Emilie Crystal'],
        to: '/emelie-crystal',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/emelieCrystal—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"emily willis",
        aliases: ['Litzy Lara Bañuelos'],
        to: '/emily-willis',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/emilyWillis—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"eva elfie",
        aliases: ['Brigitte', 'Lady Jay', 'Tieny Mieny', 'Tiny Teen'],
        to: '/evaElfie',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/evaElfie—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"evelyn claire",
        aliases: ['Evelyn', 'Evelyn Claire'],
        to: '/evelynClaire',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/evelynClaire—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"elsa jean",
        aliases: ['Elsa Dream', 'Elsa Dream Jean', 'Molly', 'Sapphire Howell'],
        to: '/elsaJean',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/elsaJean—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"freya mayer",
        // aliases: ['Freya', 'Freya Mayer'],
        to: '/freyaMayer',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/freyaMayer—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"freya parker",
        // aliases: ['Freya', 'Freya Parker'],
        to: '/freya-parker',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/freyaParker—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"georgia jones",
        aliases: ['Alison Michelle Thompson', 'Alison Thompson', 'Georgia Rose', 'Georgie Jones', 'Larysa'],
        to: '/georgia-jones',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/georgiaJones—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"gianna dior",
        aliases: ['Emily Katherine Correro'],
        to: '/giannaDior',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/giannaDior—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"gloria sol",
        aliases: ['Aaliyah', 'Cameron', 'Carolina Quito', 'Dolores', 'Gloria', 'Penelope Y', 'Sofia', 'SofieQ', 'Sophia'],
        to: '/gloriaSol',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/gloriaSol—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"haley reed",
        aliases: ['Amy May', 'Jamie Rott'],
        to: '/haleyReed',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/haleyReed—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"hazel moore",
        aliases: ['Ellie'],
        to: '/hazelMoore',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/hazelMoore—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"ivy aura",
        // aliases: ['Ivy', 'Ivy Aura'],
        to: '/ivyAura',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/ivyAura—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"ivy wolfe",
        aliases: ["Emma Scarlett", "Ivy Mckenzie"],
        to: '/ivy-wolfe',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/ivyWolfe—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"izzy lush",
        aliases: ['Ivana', 'Ivanka Lush', 'Ivy Lush', 'Ziggy Lush'],
        to: '/izzyLush',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/izzyLush—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"jane wilde",
        aliases: ['Mary Jane Wilde', 'Sophie Summers'],
        to: '/jane-wilde',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/janeWilde—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"janice griffith",
        // aliases: ['Janice', 'Janice Griffith'],
        to: '/janiceGriffith',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/janiceGriffith―index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"jaye summers",
        // aliases: ['Jaye', 'Jaye Summers'],
        to: '/jayeSummers',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/jayeSummers—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"jessie saint",
        aliases: ['Jess'],
        to: '/jessieSaint',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/jessieSaint—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"jia lissa",
        aliases: ['Julia Chirkova'],
        to: '/jiaLissa',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/jiaLissa—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"jillian janson",
        aliases: ['Jillian Brookes', 'Anna Lynn', 'Annalynn Grace', 'Jilian Janson', 'Savana Maree Dillard'],
        to: '/jillianJanson',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/jillianJanson—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"jill kassidy",
        aliases: ['Jill Cassidy'],
        to: '/jordanJackson',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/jillKassidy—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"katrina colt",
        aliases: ['Lili Lamour'],
        to: '/katrina-colt',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/katrinaColt—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"kendra sunderland",
        aliases: ['LibraryGirl'],
        to: '/kendraSunderland',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/kendraSunderland—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"kenna james",
        aliases: ['Keena James'],
        to: '/kennaJames',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/kennaJames—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"kristen scott",
        aliases: ['Kristin Scott', 'Sasha Lynn Hiltpold'],
        to: '/kristenScott',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/kristenScott—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"kyler quinn",
        aliases: ['Aubrey Dolan', 'Taylor Corbett'],
        to: '/kylerQquinn',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/kylerQuinn—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"lana rhoades",
        aliases: ['Amara Lynee Maple', 'Lana Rhodes'],
        to: '/lanaRhoades',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/lanaRhoades—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"laney grey",
        // aliases: ['Laney Grey'],
        to: '/laney-grey',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/laneyGrey—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"leah gotti",
        aliases: ['Fiona'],
        to: '/leah-gotti',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/leahGotti—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"leanne lace",
        aliases: ['Lee Anne', 'Ann', 'Leanne Lase'],
        to: '/leanne-lace',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/leanneLace—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"lena anderson",
        aliases: ['Blaire Ivory', 'jordan west', 'sloan kendricks'],
        to: '/lenaAnderson',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/lenaAnderson—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"lena reif",
        aliases: ['Katya Zartpopsi', 'Lena Y'],
        to: '/lenaReif',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/lenaReif—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"lika star",
        aliases: ['Lika Star', 'Lolly Star', 'Masha', 'Masha Cute'],
        to: '/lika-star',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/likaStar—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"lilit ariel",
        aliases: ['Ariel Angel', 'Ariela', 'Lilit A', 'Lillianne', 'Natalia Udovenko', 'Nataliya Udovenko', 'Natasha Udovenko', 'NatellaQ', 'Rufina T', 'angelsetfree'],
        to: '/lilit-ariel',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/lilitAriel—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"lilly bell",
        // aliases: ['Lilly Bell'],
        to: '/lilly-bell',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/lillyBell—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"lily larimar",
        // aliases: ["lily larimar"],
        to: '/lily-larimar',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/lilyLarimar—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"little caprice",
        aliases: ['Caprice A', 'Lola', 'Lolashut', 'Marketa', 'Lola D', 'Markéta Štroblová',],
        to: '/littleCaprice',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/littleCaprice—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"liya silver",
        aliases: ['Kristina Shcherbinina', 'Lila Silver', 'MedinaQ'],
        to: '/liyaSilver',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/liyaSilver—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"lottie magne",
        aliases: ['Lottie Mange', 'Nada A', 'Olivia Lush'],
        to: '/lottie-magne',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/lottieMagne—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"lexi dona",
        // aliases: ['Armani Black', 'Armani'],
        to: '/lexi-dona',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/lexiDona—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"madi collins",
        aliases: ['Madicollinsxo'],
        to: '/madi-collins',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/madiCollins—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"maddy may",
        aliases: ['Maddie May'],
        to: '/maddyMay',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/maddyMay—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"marley brinx",
        liases: ['Erika Lynne Wood'],
        to: '/marley-brinx',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/marleyBrinx—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"mazzy grace",
        // liases: ['Erika Lynne Wood'],
        to: '/mazzy-grace',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/mazzyGrace—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"melena maria rya",
        aliases: ['Maria', 'Melena A', 'Maria Ryabushkina', 'Marta', 'Melina A', 'Melina Maria', 'Melina Tara', 'SexySu4ka', 'Tara'],
        to: '/melenaMariaRya',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/melenaMariaRya—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"melody marks",
        aliases: ['Melody Hina Marks'],
        to: '/melody-marks',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/melodyMarks—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"mila azul",
        aliases: ['Ekaterina Volkova', 'Elena D', 'Jane Y.', 'Mia I', 'Mila A', 'Mila Azil', 'Mila S', 'Milla', 'Milla Azul', 'Milla D', 'Milla Y', 'Mylen Branna'],
        to: '/milaAzul',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/milaAzul—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"molly little",
        // aliases: ['Molly A', 'Molly Little', 'Molly Y'],
        to: '/mollyLittle',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/mollyLittle—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"nancy ace",
        aliases: ['Anastasiya Shubeyko', 'Anastasiya Yanuskova', 'Dominic Anne', 'Erika', 'Jane', 'Nancy A', 'Nancy Ambrosia', 'Nancy Karl', 'Nancy Y'],
        to: '/nancyAce',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/nancyAce—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"naomi swann",
        aliases: ['Naomi Swan',' Nayomi', 'Princess Naomi Swann'],
        to: '/naomiSwann',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/naomiSwann—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"oxana chic",
        aliases: ['Oxana Z'],
        to: '/oxana-chic',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/oxanaChic—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"rebecca volpetti",
        aliases: ["Sorina", "Anna Italyanka", "Catia A", "Kristina Zaharia"],
        to: '/rebecca-volpetti',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/rebeccaVolpetti—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"ria sunn",
        aliases: ['Nikola', 'Amanda', 'Cici', 'Denisa', 'Isabell', 'Riaa'],
        to: '/riaSunn',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/riaSunn—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"rika fane",
        aliases: ['Hana Džurbanová', 'Hannah Baisiol'],
        to: '/rikaFane',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/rikaFane—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"riley reid",
        aliases: ['Ashley Mathews', 'Luiselle', 'Molly', 'Paige Riley', 'Riley Reed'],
        to: '/rileyReid',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/rileyReid—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"scarlit scandal",
        aliases: ['Skarlitt Scandal'],
        to: '/scarlitScandal',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/scarlitScandal—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"sophia leone",
        aliases: ['Sophie Leone'],
        to: '/sophia-leone',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/sophiaLeone—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },
    {
        id: uuidv4(),
        title:"stacy cruz",
        aliases: ['Cornelia', 'Little Pia', 'Stacy Kruz', 'Tina'],
        to: '/stacyCruz',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/stacyCruz—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"sybil",
        aliases: ['Kailena', 'Davina E',' Sybil Kailena', 'Dani', 'Dani Volkova', 'Davina', 'Olga Sybil', 'Olga Volkova', 'Sibil', 'Sybil A Kailena', 'Sybille Y', 'Sybil A'],
        to: '/sybil',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/sybil—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"tiffany tatum",
        aliases: ['Enzio Ricci'],
        to: '/tiffanyTatum',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/tiffanyTatum—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"tori black",
        aliases: ['Michelle Chapman'],
        to: '/toriBlack',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/toriBlack—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"uma jolie",
        aliases: ['Belecia', 'Belicia', 'Belicia Segura', 'Luna', 'Madeline Clarck'],
        to: '/umaJolie',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/umaJolie—index.jpg",
        color: 'hotpink',
        txtcolor: 'white',
    },
    {
        id: uuidv4(),
        title:"valentina nappi",
        to: '/valentina-nappi',
        image:"https://raw.githubusercontent.com/laboo25/mag-imgs/main/index/valentinaNappi—index.jpg",
        color: 'white',
        txtcolor: 'black',
    },

]
